### ISSUE TITLE
[Bug] Settings panel close when toggle status bar

### ISSUE THREAD

**Issue by joexmdq** [JasonStein/Notepads#525] opened 2020-05-12 02:24 UTC
**Describe the bug**
The settings panel close itself when you toggle the status bar visibility

**To Reproduce**
1. Go to Settings > Advance
2. Toggle "Show status bar" on or off

**Expected behavior**
Status bar toggles without the settings panel disappearing

**Screenshots**
![](https://i.imgur.com/Ztv7C6M.gif)

**Desktop**
 - OS: Windows 10 Pro 1909 - 18363.778
 - Notepads: v1.3.1.0

**Additional context**
N/A

**Comment by JasonStein** [comment] 2020-05-12 02:53
This is an intended behavior since the height will change in that case. It is not going to affect your day to day use since you will not switching this option on and off quite often, don't you?

**Comment by joexmdq** [comment] 2020-05-12 23:47
> This is an intended behavior since the height will change in that case. It is not going to affect your day to day use since you will not switching this option on and off quite often, don't you?

True, but I do think it's really an unexpected behaviour, The height change can cause some problem or is just to prevent the blank space below? Personally I would rather prefer that than closing the panel. Anyways, I understand is not that big of a deal.

**Comment by JasonStein** [comment] 2020-06-04 18:07
> > This is an intended behavior since the height will change in that case. It is not going to affect your day to day use since you will not switching this option on and off quite often, don't you?
> 
> True, but I do think it's really an unexpected behaviour, The height change can cause some problem or is just to prevent the blank space below? Personally I would rather prefer that than closing the panel. Anyways, I understand is not that big of a deal.

It hides itself automatically when size changed and the panel is a system control which I have less control over. Closing this thread since it might not be fixed anytime soon and not quite worth the effort here.

**Closed by JasonStein** 2020-06-04 18:07 UTC
