### ISSUE TITLE
[Feature request] Search Enhancement

### ISSUE THREAD

**Issue by Threonine-Animist** [JasonStein/Notepads#120] opened 2019-08-09 04:48 UTC
1.It might be better if Notepads can search instantly when some words is typed in searchbox.
Making the matched highlighted in the scrollbar also sounds great. Just like what Chrome does.
2.Please make the availability of F3 function all the time. In current version F3 is available only when the searchbox is open.

**Comment by JasonStein** [comment] 2019-08-09 05:13
For option 1, I have a plan but not sure if it is doable by design, I will try my best anyway.
For option 2, let me think about it. It is a valid suggestion tho.

**Comment by United600** [comment] 2019-12-08 02:10
Not to hijack this issue but the ability to switch input fields with the Shift key would rock

**Comment by JasonStein** [comment] 2020-04-17 03:33
Enhancements have been made to Find and Replace. Closing this thread for now.

**Closed by JasonStein** 2020-04-17 03:33 UTC
