### ISSUE TITLE
Can't use Alt Gr

### ISSUE THREAD

**Issue by Grompie** [JasonStein/Notepads#4] opened 2019-07-02 08:27 UTC
Typing # or @ doesn't work on my Azerty keyboard since you need to use the Alt Gr key to type those characters. (https://images.app.goo.gl/KNSX2AvUCjpGCAwKA => layout of Azerty keyboard)

**Comment by JasonStein** [comment] 2019-07-02 20:00
Hi Grompie, thanks for reporting. I am aware of it as well as it has been reported by another French user as well. However I am not sure how to handle it yet (Since AltGr is equal to ctrl+alt hitting and same time). I will keep you posted if I can fix it.

**Comment by validatedev** [comment] 2019-07-03 08:38
The same issue has been happened with Turkish-Q keyboard

**Comment by JasonStein** [comment] 2019-07-03 09:09
@Grompie  @validatedev  Can you guys join Notepads' discord server and we can debug together to see if I can fix it?

**Comment by frousselet** [comment] 2019-07-03 09:57
Hello,

Thanks for your great work.

I confirm the issue with french AZERTY keyboards. Cannot user AltGr or Ctrl+Alt.

The Terminal Beta app from Microsoft team had a similar issue, but it has been fixed (https://github.com/microsoft/terminal/pull/1436). I don't know if it's the same problem for your app.

**Comment by glitchroy** [comment] 2019-07-03 13:56
Confirmed for QWERTZ layout (German).  
Interesting side note, the € symbol (modifier for E) works with CTRL+ALT+E, but not with ALTGR+E, while the other modifiers (e.g. {) do not work with either CTRL+ALT+7, nor ALTGR+7.  It's not related to the number row either, since the @ symbol (modifier for Q) and the µ symbol (modifier for M) also do not work with CTRL+ALT.

**Comment by JasonStein** [comment] 2019-07-04 05:19
Two PRs merged to fix the issue:

- https://github.com/JasonStein/Notepads/commit/c0eddcab0ca2ee63f18326f71e46e2f8a50e0367
- https://github.com/JasonStein/Notepads/pull/5

Please wait for few days before your app gets the update. It will be fixed in v0.9.3.0.

**Comment by JasonStein** [comment] 2019-07-05 18:17
Close this one since it has been fixed in v0.9.3.0 and it is available in Microsoft Store as well.

**Closed by JasonStein** 2019-07-05 18:17 UTC
Labels: Fixed, bug
