### ISSUE TITLE
[Bug] Line limit?

### ISSUE THREAD

**Issue by maydoc** [JasonStein/Notepads#787] opened 2021-02-22 01:58 UTC
Hello, I have a text file with 13 digits codes separated by line, and in this file there are 59880 lines / codes, the file is approximately 878 KB, however when viewing the file, from line 12079 the codes disappear, I can still select, but it does not appear, I tested it on Notepad++ and the codes normally appeared until 59880.

![image](https://user-images.githubusercontent.com/70946246/108647697-16b8e880-7498-11eb-9b54-86925d66fe52.png)

**Comment by XamDR** [comment] 2021-03-07 15:57
Hi. This is a known bug related to the underlying RichEditBox control. Also a duplicate of [this](https://github.com/JasonStein/Notepads/issues/700) and [this](https://github.com/JasonStein/Notepads/issues/373).

**Comment by JasonStein** [comment] 2021-03-21 04:06
Known issue for now.

**Closed by JasonStein** 2021-03-21 04:06 UTC
