### ISSUE TITLE
[Bug] Black rectangle behind markdown preview's context menu

### ISSUE THREAD

**Issue by AmionSky** [JasonStein/Notepads#84] opened 2019-07-23 12:10 UTC
**Describe the bug**
During closeing animation:
![Screenshot 2019-07-23 13 58 05](https://user-images.githubusercontent.com/13593262/61710732-8d3cb400-ad52-11e9-8403-10117460ea64.png)
When opened at window bottom:
![Screenshot 2019-07-23 13 57 51](https://user-images.githubusercontent.com/13593262/61710733-8d3cb400-ad52-11e9-873a-637d55d947ea.png)
![Screenshot 2019-07-23 14 09 10](https://user-images.githubusercontent.com/13593262/61711104-90846f80-ad53-11e9-96e3-bf6f2860cad0.png)

**To Reproduce**
- Open markdown preview.
- Right-click at the bottom of the window

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 18362.239
 - Version: 4571fa156a8c49d6423570272bf08040d04a79c2

**Comment by JasonStein** [comment] 2019-07-23 14:26
This is definitely some windows bug.......

**Comment by JasonStein** [comment] 2019-07-23 18:20
I can confirm this is a system bug....
![image](https://user-images.githubusercontent.com/1166162/61736865-e3eac380-ad3b-11e9-8544-fb26ca7a2d34.png)

**Comment by JasonStein** [comment] 2019-08-08 06:41
Close this since it is Windows bug

**Closed by JasonStein** 2019-08-08 06:41 UTC
Labels: wontfix

**Comment by JasonStein** [comment] 2019-10-03 08:41
@AmionSky  This is fixed by targeting Windows 1903 SDK.
